<?php

return [
    [
        'label'  => '汉族',
        'value'  => 'Han',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '壮族',
        'value'  => 'Zhuang',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '满族',
        'value'  => 'Man',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '回族',
        'value'  => 'Hui',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '苗族',
        'value'  => 'Miao',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '维吾尔族',
        'value'  => 'Weiwuer',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '土家族',
        'value'  => 'Tujia',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '彝族',
        'value'  => 'Yi',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '蒙古族',
        'value'  => 'Menggu',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '藏族',
        'value'  => 'Zang',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '布依族',
        'value'  => 'Buyi',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '侗族',
        'value'  => 'Dong',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '瑶族',
        'value'  => 'Yao',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '朝鲜族',
        'value'  => 'Chaoxian',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '白族',
        'value'  => 'Bai',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '哈尼族',
        'value'  => 'Hani',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '哈萨克族',
        'value'  => 'Hasake',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '黎族',
        'value'  => 'Li',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '傣族',
        'value'  => 'Dai',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '畲族',
        'value'  => 'She',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '傈僳族',
        'value'  => 'Lisu',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '仡佬族',
        'value'  => 'Gelao',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '东乡族',
        'value'  => 'Dongxiang',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '高山族',
        'value'  => 'Gaoshan',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '拉祜族',
        'value'  => 'Lahu',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '水族',
        'value'  => 'Shui',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '佤族',
        'value'  => 'Wa',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '纳西族',
        'value'  => 'Naxi',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '羌族',
        'value'  => 'Qiang',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '土族',
        'value'  => 'Tu',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '仫佬族',
        'value'  => 'Mulao',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '锡伯族',
        'value'  => 'Xibo',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '柯尔克孜族',
        'value'  => 'Keerkezi',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '达斡尔族',
        'value'  => 'Dawoer',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '景颇族',
        'value'  => 'Jingpo',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '毛南族',
        'value'  => 'Maonan',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '撒拉族',
        'value'  => 'Sala',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '布朗族',
        'value'  => 'Bulang',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '塔吉克族',
        'value'  => 'Tajike',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '阿昌族',
        'value'  => 'Achang',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '普米族',
        'value'  => 'Pumi',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '鄂温克族',
        'value'  => 'Ewenke',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '怒族',
        'value'  => 'Nu',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '京族',
        'value'  => 'Jing',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '基诺族',
        'value'  => 'Jinuo',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '德昂族',
        'value'  => 'Deang',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '保安族',
        'value'  => 'Baoan',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '俄罗斯族',
        'value'  => 'Eluosi',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '裕固族',
        'value'  => 'Yugu',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '乌孜别克族',
        'value'  => 'Wuzibieke',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '门巴族',
        'value'  => 'Menba',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '鄂伦春族',
        'value'  => 'Elunchun',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '独龙族',
        'value'  => 'Dulong',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '塔塔尔族',
        'value'  => 'Tataer',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '赫哲族',
        'value'  => 'Hezhe',
        'code'   => 'nation',
        'remark' => '',
    ],
    [
        'label'  => '珞巴族',
        'value'  => 'Luoba',
        'code'   => 'nation',
        'remark' => '',
    ],
];
