<?php

use Modules\Admin\Classes\Utils\SystemConfigInputType;

return [
    [
        'group'              => 'wechat_config',
        'key'                => 'wechat_group',
        'value'              => 'wechat_mini',
        'name'               => '当前配置',
        'input_type'         => SystemConfigInputType::TABS,
        'config_select_data' => [
            ['label' => '小程序', 'value' => 'wechat_mini'],
            ['label' => '公众号', 'value' => 'wechat_official'],
            ['label' => '支付', 'value' => 'wechat_pay'],
        ],
        'remark'        => '',
        'bind_p_config' => '',
        'input_attr'    => null,
    ],
    [
        'group'              => 'wechat_config',
        'key'                => 'wechat_mini_app_id',
        'value'              => '',
        'name'               => 'app id',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => [],
        'remark'             => '微信小程序app id',
        'bind_p_config'      => 'wechat_group',
        'input_attr'         => null,
    ],
    [
        'group'              => 'wechat_config',
        'key'                => 'wechat_mini_secret',
        'value'              => '',
        'name'               => 'secret',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => [],
        'remark'             => '微信小程序secret',
        'bind_p_config'      => 'wechat_group',
        'input_attr'         => null,
    ],
    [
        'group'              => 'wechat_config',
        'key'                => 'wechat_official_app_id',
        'value'              => '',
        'name'               => 'app id',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => [],
        'remark'             => '微信公众号app id',
        'bind_p_config'      => 'wechat_group',
        'input_attr'         => null,
    ],
    [
        'group'              => 'wechat_config',
        'key'                => 'wechat_official_secret',
        'value'              => '',
        'name'               => 'secret',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => [],
        'remark'             => '微信公众号secret',
        'bind_p_config'      => 'wechat_group',
        'input_attr'         => null,
    ],
    [
        'group'              => 'wechat_config',
        'key'                => 'wechat_pay_mch_id',
        'value'              => '',
        'name'               => '商户号',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => [],
        'remark'             => '',
        'bind_p_config'      => 'wechat_group',
        'input_attr'         => null,
    ],
    [
        'group'              => 'wechat_config',
        'key'                => 'wechat_pay_mch_secret_key',
        'value'              => null,
        'name'               => '商户秘钥',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => [],
        'remark'             => '',
        'bind_p_config'      => 'wechat_group',
        'input_attr'         => null,
    ],
    [
        'group'              => 'wechat_config',
        'key'                => 'wechat_pay_mch_secret_cert',
        'value'              => '',
        'name'               => '商户私钥',
        'input_type'         => SystemConfigInputType::UPLOAD_FILE,
        'config_select_data' => [],
        'remark'             => '',
        'bind_p_config'      => 'wechat_group',
        'input_attr'         => ['mode' => 'resource', 'filename' => 'mch_secret_cert', 'accept' => '.pem'],
    ],
    [
        'group'              => 'wechat_config',
        'key'                => 'wechat_pay_mch_public_cert',
        'value'              => '',
        'name'               => '商户公钥',
        'input_type'         => SystemConfigInputType::UPLOAD_FILE,
        'config_select_data' => [],
        'remark'             => '',
        'bind_p_config'      => 'wechat_group',
        'input_attr'         => ['mode' => 'resource', 'filename' => 'mch_public_cert', 'accept' => '.pem'],
    ],
];
