<?php

use Modules\Admin\Classes\Utils\SystemConfigInputType;

return [
    /*
    |--------------------------------------------------------------------------
    | 类型限制
    |--------------------------------------------------------------------------
    */
    [
        'group'      => 'upload_config',
        'name'       => '类型限制',
        'input_type' => SystemConfigInputType::DIVIDER,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'upload_allow_file',
        'value'              => 'jpg,jpeg,png,gif,svg,bmp,doc,docx,xls,xlsx,ppt,pptx,pdf,md,mp3,mp4,mov',
        'name'               => '文件类型',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => '',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'upload_allow_image',
        'value'              => 'jpg,jpeg,png,gif,svg,bmp',
        'name'               => '图片类型',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => '',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'upload_allow_video',
        'value'              => 'mp4',
        'name'               => '视频类型',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => '',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'upload_allow_audio',
        'value'              => 'mp3',
        'name'               => '音频类型',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => '',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'upload_allow_document',
        'value'              => 'txt,doc,docx,xls,xlsx,ppt,pptx,pdf,md',
        'name'               => '文稿类型',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => '',
        'input_attr'         => null,
    ],
    /*
    |--------------------------------------------------------------------------
    | 大小限制
    |--------------------------------------------------------------------------
    */
    [
        'group'      => 'upload_config',
        'name'       => '大小限制',
        'input_type' => SystemConfigInputType::DIVIDER,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'upload_size',
        'value'              => '10485760',
        'name'               => '上传文件大小',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '单位Byte,1MB=1024*1024Byte',
        'bind_p_config'      => null,
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'upload_size_image',
        'value'              => '1048576',
        'name'               => '上传图片大小',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '单位Byte,1MB=1024*1024Byte',
        'bind_p_config'      => '',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'upload_size_video',
        'value'              => '10485760',
        'name'               => '上传视频大小',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '单位Byte,1MB=1024*1024Byte',
        'bind_p_config'      => '',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'upload_size_audio',
        'value'              => '10485760',
        'name'               => '上传音频大小',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '单位Byte,1MB=1024*1024Byte',
        'bind_p_config'      => '',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'upload_size_document',
        'value'              => '10485760',
        'name'               => '上传文稿大小',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '单位Byte,1MB=1024*1024Byte',
        'bind_p_config'      => '',
        'input_attr'         => null,
    ],
    /*
    |--------------------------------------------------------------------------
    | 存储类型
    |--------------------------------------------------------------------------
    */
    [
        'group'      => 'upload_config',
        'name'       => '存储类型',
        'input_type' => SystemConfigInputType::DIVIDER,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'storage_mode',
        'value'              => 'public',
        'name'               => '默认存储',
        'input_type'         => SystemConfigInputType::RADIO,
        'config_select_data' => [
            ['label' => '本地私有', 'value' => 'local'],
            ['label' => '本地公开', 'value' => 'public'],
            ['label' => '阿里云OSS', 'value' => 'oss'],
            ['label' => '七牛云', 'value' => 'qiniu'],
            ['label' => '腾讯云COS', 'value' => 'cos'],
            ['label' => '亚马逊S3', 'value' => 's3'],
        ],
        'remark'        => '',
        'bind_p_config' => '',
        'input_attr'    => null,
    ],
    /*
    |--------------------------------------------------------------------------
    | 存储类型 - 本地私有
    |--------------------------------------------------------------------------
    */
    [
        'group'         => 'upload_config',
        'key'           => 'local_status',
        'value'         => 'normal',
        'name'          => '本地私有状态',
        'input_type'    => SystemConfigInputType::DICT_RADIO,
        'remark'        => '本地私有状态',
        'bind_p_config' => 'storage_mode',
        'input_attr'    => [
            'code'  => 'data_status',
            'type'  => 'info',
            'merge' => [
                'normal' => [
                    'label'  => '启用',
                    'remark' => '正常上传文件</br>此存储外部无法访问',
                ],
                'disabled' => [
                    'label'  => '停用',
                    'remark' => '上传到此存储将不可用</br>已上传文件不受影响',
                ],
            ],
        ],
    ],
    /*
    |--------------------------------------------------------------------------
    | 存储类型 - 本地公开
    |--------------------------------------------------------------------------
    */
    [
        'group'              => 'upload_config',
        'key'                => 'public_status',
        'value'              => 'normal',
        'name'               => '本地存储状态',
        'input_type'         => SystemConfigInputType::DICT_RADIO,
        'config_select_data' => [
            ['label' => '启用', 'value' => 'normal'],
            ['label' => '停用', 'value' => 'disabled'],
        ],
        'remark'        => '本地存储状态',
        'bind_p_config' => 'storage_mode',
        'input_attr'    => [
            'code'  => 'data_status',
            'type'  => 'info',
            'merge' => [
                'normal' => [
                    'label'  => '启用',
                    'remark' => '正常上传文件对外可访问</br>需注意服务器带宽资源消耗',
                ],
                'disabled' => [
                    'label'  => '停用',
                    'remark' => '上传到此存储将不可用</br>已上传文件不受影响',
                ],
            ],
        ],
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'public_domain',
        'value'              => 'http://127.0.0.1:8000',
        'name'               => '本地存储域名',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '本地存储域名',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    /*
    |--------------------------------------------------------------------------
    | 存储类型 - 七牛云
    |--------------------------------------------------------------------------
    */
    [
        'group'              => 'upload_config',
        'key'                => 'qiniu_status',
        'value'              => 'disabled',
        'name'               => '七牛云状态',
        'input_type'         => SystemConfigInputType::DICT_RADIO,
        'config_select_data' => [
            ['label' => '启用', 'value' => 'normal'],
            ['label' => '停用', 'value' => 'disabled'],
        ],
        'remark'        => '七牛云状态',
        'bind_p_config' => 'storage_mode',
        'input_attr'    => [
            'code'  => 'data_status',
            'type'  => 'info',
            'merge' => [
                'normal' => [
                    'label'  => '启用',
                    'remark' => '正常上传文件</br>更多信息请访问<a class="arco-link arco-link-status-normal" style="padding: 0 2px;line-height:1;" href="https://developer.qiniu.com/kodo" target="_blank">七牛云</a>',
                ],
                'disabled' => [
                    'label'  => '停用',
                    'remark' => '上传到此存储将不可用</br>已上传文件不受影响',
                ],
            ],
        ],
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'qiniu_accessKey',
        'value'              => '',
        'name'               => '七牛key',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '七牛云存储secretId',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'qiniu_secretKey',
        'value'              => '',
        'name'               => '七牛secret',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '七牛云存储secretKey',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'qiniu_bucket',
        'value'              => '',
        'name'               => '七牛bucket',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '七牛云存储bucket',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'qiniu_dirname',
        'value'              => '',
        'name'               => '七牛dirname',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '七牛云存储dirname',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'qiniu_domain',
        'value'              => '',
        'name'               => '七牛domain',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '七牛云存储domain',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    /*
    |--------------------------------------------------------------------------
    | 存储类型 - 腾讯云
    |--------------------------------------------------------------------------
    */
    [
        'group'              => 'upload_config',
        'key'                => 'cos_status',
        'value'              => 'disabled',
        'name'               => '腾讯云状态',
        'input_type'         => SystemConfigInputType::DICT_RADIO,
        'config_select_data' => [
            ['label' => '启用', 'value' => 'normal'],
            ['label' => '停用', 'value' => 'disabled'],
        ],
        'remark'        => '腾讯云状态',
        'bind_p_config' => 'storage_mode',
        'input_attr'    => [
            'code'  => 'data_status',
            'type'  => 'info',
            'merge' => [
                'normal' => [
                    'label'  => '启用',
                    'remark' => '正常上传文件</br>更多信息请访问<a class="arco-link arco-link-status-normal" style="padding: 0 2px;line-height:1;" href="https://cloud.tencent.com/document/product/436" target="_blank">腾讯云</a>',
                ],
                'disabled' => [
                    'label'  => '停用',
                    'remark' => '上传到此存储将不可用</br>已上传文件不受影响',
                ],
            ],
        ],
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'cos_secretId',
        'value'              => '',
        'name'               => '腾讯Id',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '腾讯云存储secretId',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'cos_secretKey',
        'value'              => '',
        'name'               => '腾讯key',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '腾讯云secretKey',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'cos_bucket',
        'value'              => '',
        'name'               => '腾讯bucket',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '腾讯云存储bucket',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'cos_dirname',
        'value'              => '',
        'name'               => '腾讯dirname',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '腾讯云存储dirname',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'cos_domain',
        'value'              => '',
        'name'               => '腾讯domain',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '腾讯云存储domain',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'cos_region',
        'value'              => '',
        'name'               => '腾讯region',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '腾讯云存储region',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    /*
    |--------------------------------------------------------------------------
    | 存储类型 - 阿里云
    |--------------------------------------------------------------------------
    */
    [
        'group'              => 'upload_config',
        'key'                => 'oss_status',
        'value'              => 'disabled',
        'name'               => '阿里云状态',
        'input_type'         => SystemConfigInputType::DICT_RADIO,
        'config_select_data' => [
            ['label' => '启用', 'value' => 'normal'],
            ['label' => '停用', 'value' => 'disabled'],
        ],
        'remark'        => '阿里云状态',
        'bind_p_config' => 'storage_mode',
        'input_attr'    => [
            'code'  => 'data_status',
            'type'  => 'info',
            'merge' => [
                'normal' => [
                    'label'  => '启用',
                    'remark' => '正常上传文件</br>更多信息请访问<a class="arco-link arco-link-status-normal" style="padding: 0 2px;line-height:1;" href="https://help.aliyun.com/zh/oss/" target="_blank">阿里云</a>',
                ],
                'disabled' => [
                    'label'  => '停用',
                    'remark' => '上传到此存储将不可用</br>已上传文件不受影响',
                ],
            ],
        ],
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'oss_accessKeyId',
        'value'              => '',
        'name'               => '阿里Id',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '阿里云存储accessKeyId',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'oss_accessKeySecret',
        'value'              => '',
        'name'               => '阿里Secret',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '阿里云存储accessKeySecret',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'oss_bucket',
        'value'              => '',
        'name'               => '阿里bucket',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '阿里云存储bucket',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'oss_dirname',
        'value'              => '',
        'name'               => '阿里dirname',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '阿里云存储dirname',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'oss_domain',
        'value'              => '',
        'name'               => '阿里domain',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '阿里云存储domain',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 'oss_endpoint',
        'value'              => '',
        'name'               => '阿里endpoint',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '阿里云存储endpoint',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    /*
    |--------------------------------------------------------------------------
    | 存储类型 - 亚马逊s3
    |--------------------------------------------------------------------------
    */
    [
        'group'              => 'upload_config',
        'key'                => 's3_status',
        'value'              => 'disabled',
        'name'               => 's3状态',
        'input_type'         => SystemConfigInputType::DICT_RADIO,
        'config_select_data' => [
            ['label' => '启用', 'value' => 'normal'],
            ['label' => '停用', 'value' => 'disabled'],
        ],
        'remark'        => 's3状态',
        'bind_p_config' => 'storage_mode',
        'input_attr'    => [
            'code'  => 'data_status',
            'type'  => 'info',
            'merge' => [
                'normal' => [
                    'label'  => '启用',
                    'remark' => '正常上传文件</br>更多信息请访问<a class="arco-link arco-link-status-normal" style="padding: 0 2px;line-height:1;" href="https://www.amazonaws.cn/s3/" target="_blank">亚马逊s3</a>',
                ],
                'disabled' => [
                    'label'  => '停用',
                    'remark' => '上传到此存储将不可用</br>已上传文件不受影响',
                ],
            ],
        ],
    ],
    [
        'group'              => 'upload_config',
        'key'                => 's3_key',
        'value'              => '',
        'name'               => 'key',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 's3_secret',
        'value'              => '',
        'name'               => 'secret',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 's3_bucket',
        'value'              => '',
        'name'               => 'bucket',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 's3_dirname',
        'value'              => '',
        'name'               => 'dirname',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 's3_domain',
        'value'              => '',
        'name'               => 'domain',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 's3_region',
        'value'              => '',
        'name'               => 'region',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 's3_version',
        'value'              => '',
        'name'               => 'version',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 's3_use_path_style_endpoint',
        'value'              => '',
        'name'               => 'path_style_endpoint',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 's3_endpoint',
        'value'              => '',
        'name'               => 'endpoint',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],
    [
        'group'              => 'upload_config',
        'key'                => 's3_acl',
        'value'              => '',
        'name'               => 'acl',
        'input_type'         => SystemConfigInputType::INPUT,
        'config_select_data' => null,
        'remark'             => '',
        'bind_p_config'      => 'storage_mode',
        'input_attr'         => null,
    ],

];
