<?php

use Modules\Admin\Classes\Utils\SystemConfigInputType;

return [
    [
        'group' => 'site_config',
        'key'   => 'site_copyright',
        'value' => '@2025 - 2025 Laravel后台管理模板',
        'name'  => [
            'zh_CN' => '版权信息',
            'en'    => 'Copyright Information',
        ],
        'input_type'    => SystemConfigInputType::TEXTAREA,
        'remark'        => '',
        'bind_p_config' => null,
        'input_attr'    => null,
    ],
    [
        'group' => 'site_config',
        'key'   => 'site_desc',
        'value' => 'Laravel后台管理模板',
        'name'  => [
            'zh_CN' => '网站描述',
            'en'    => 'Site Description',
        ],
        'input_type'    => SystemConfigInputType::TEXTAREA,
        'remark'        => null,
        'bind_p_config' => null,
        'input_attr'    => null,
    ],
    [
        'group' => 'site_config',
        'key'   => 'site_keywords',
        'value' => 'Laravel后台管理模板',
        'name'  => [
            'zh_CN' => '网站关键字',
            'en'    => 'Site Keywords',
        ],
        'input_type'    => SystemConfigInputType::INPUT,
        'remark'        => null,
        'bind_p_config' => null,
        'input_attr'    => null,
    ],
    [
        'group' => 'site_config',
        'key'   => 'site_name',
        'value' => 'Laravel后台管理模板',
        'name'  => [
            'zh_CN' => '网站名称',
            'en'    => 'Site Name',
        ],
        'input_type'    => SystemConfigInputType::INPUT,
        'remark'        => null,
        'bind_p_config' => null,
        'input_attr'    => null,
    ],
    [
        'group' => 'site_config',
        'key'   => 'site_record_number',
        'value' => '1234567890',
        'name'  => [
            'zh_CN' => '网站备案号',
            'en'    => 'Site Record Number',
        ],
        'input_type'    => SystemConfigInputType::INPUT,
        'remark'        => null,
        'bind_p_config' => null,
        'input_attr'    => null,
    ],
    [
        'group' => 'site_config',
        'key'   => 'about',
        'value' => '',
        'name'  => [
            'zh_CN' => '关于我们',
            'en'    => 'About Us',
        ],
        'input_type'    => SystemConfigInputType::WANG_EDITOR,
        'remark'        => '',
        'bind_p_config' => '',
        'input_attr'    => null,
    ],
    [
        'group' => 'site_config',
        'key'   => 'join_about',
        'value' => '',
        'name'  => [
            'zh_CN' => '加入我们',
            'en'    => 'Join Us',
        ],
        'input_type'    => SystemConfigInputType::WANG_EDITOR,
        'remark'        => '',
        'bind_p_config' => '',
        'input_attr'    => null,
    ],
    [
        'group' => 'site_config',
        'key'   => 'address',
        'value' => '星系信息寻寻寻寻寻寻寻寻寻寻寻寻寻寻寻C座605室',
        'name'  => [
            'zh_CN' => '公司地址',
            'en'    => 'Company Address',
        ],
        'input_type'    => SystemConfigInputType::INPUT,
        'remark'        => '',
        'bind_p_config' => null,
        'input_attr'    => null,
    ],
    [
        'group' => 'site_config',
        'key'   => 'phone',
        'value' => '020-12345678',
        'name'  => [
            'zh_CN' => '联系电话',
            'en'    => 'Contact Phone',
        ],
        'input_type'    => SystemConfigInputType::INPUT,
        'remark'        => '',
        'bind_p_config' => null,
        'input_attr'    => null,
    ],
    [
        'group' => 'site_config',
        'key'   => 'service_phone',
        'value' => '020-12345678',
        'name'  => [
            'zh_CN' => '客服电话',
            'en'    => 'Service Phone',
        ],
        'input_type'    => SystemConfigInputType::INPUT,
        'remark'        => '',
        'bind_p_config' => null,
        'input_attr'    => null,
    ],
];
